repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.2
    hooks:
      - id: ruff
        types_or: [ python, pyi ]
        args: ["--fix", "--show-fixes"]
      - id: ruff-format
        types_or: [ python, pyi ]
